### ISSUE TITLE
Wizards' Guild advertising

### ISSUE THREAD

**Issue by Samgotdam** [Samgotdam/Elemental2#1]
as an online store Wizards' Guild wants to display advertisements for sale on a Wizards' Store site, a Wizard’s Hat and a Magic Wand so they can make more money.

**Comment by oppenheip** [comment]
They don't want to display advertisements for sale. They want a page that sells a hat and a page that sells a wand. On Moodle, you can find the screen mockups.

**Comment by oppenheip** [comment]
Write this as a user story. As a [user]... Don't write it from the online store's point of view.
