### ISSUE TITLE
As a Wizards' Guild Member, I want to be able to navigate back to the Main Elemental Screens from a link at the bottom of each page so that I can quickly navigate the site.

### ISSUE THREAD

**Issue by Samgotdam** [Samgotdam/Elemental2#2]
As a Wizards' Guild Member, I want to be able to navigate back to the Main Elemental Screens from a link at the bottom of each page so that I can quickly navigate the site.

**Comment by oppenheip** [comment]
Write this as a User Story. See the PowerPoints for Week 1, Week 3, Week 8.

They each have this slide:

<img width="917" alt="Screen Shot 2020-11-19 at 9 47 16 AM" src="https://user-images.githubusercontent.com/15792096/99703674-3df0bb80-2a4c-11eb-970f-55b0fed35a13.png">

**Comment by oppenheip** [comment]
Thanks for fixing it. :-)

**Comment by Samgotdam** [comment]
I added the following link to each elemental page per member request to ensure users can quickly navigate the Wizards' Guild site
<a href="index.html">
Return to the Main Element Screen...
</a>
<hr>
